# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, user, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/564ef2c6-23b2-4fbe-93d7-5168f3f0bf9c";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/6A01-190D";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  # TODO: Make Steam use this drive as a library
  fileSystems."/home/${user}/Games" = {
    device = "/dev/disk/by-uuid/d90fbc76-b236-4f53-b880-6400df274bb8";
    fsType = "ext4";
    options = [
      #"defaults"
      #"users" # Mount and dismount user perm
      #"noatime"
      #"nodiratime"
      #"nofail" # No system fail if driver doesn't mount
      #"uid=1000"
      #"gid=100"
      #"utf8"
      #"dmask=027"
      #"fmask=007"
      #"rw"
      #"exec"
      #"umask=000"
      #"x-gvfs-show" # Show disk in file explorer
      #"X-mount.mkdir" # Make directory if it doesn't exist
      "X-mount.owner=${user}"
      "X-mount.group=users"
    ];
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/cf8460fc-881f-483f-a693-442d9967b991"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
